version:  '3'

services:
    comidappDb:
        image: postgres:15.3
        container_name: comidapp-db
        restart: always
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: comidappuser
            POSTGRES_PASSWORD: comidapppass
            POSTGRES_DB: comidapp
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
